---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  interval: 1h
  ref:
    branch: main
  url: https://github.com/AnkSha44/instavote-deploy.git
